//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cadencii.Properties
{
    using System;


    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cadencii.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   (アイコン) に類似した型 Xwt.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage _switch
        {
            get
            {
                object obj = ResourceManager.GetObject("_switch", resourceCulture);
				return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage alarm_clock
        {
            get
            {
                object obj = ResourceManager.GetObject("alarm_clock", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_090
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_090", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_135
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_135", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_180
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_180", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_270
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_270", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_circle_double
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_return
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_return", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_skip
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_skip", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_skip_090
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_skip_090", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage arrow_skip_180
        {
            get
            {
                object obj = ResourceManager.GetObject("arrow_skip_180", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage btn1
        {
            get
            {
                object obj = ResourceManager.GetObject("btn1", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage btn2
        {
            get
            {
                object obj = ResourceManager.GetObject("btn2", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage btn3
        {
            get
            {
                object obj = ResourceManager.GetObject("btn3", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage chevron_small_collapse
        {
            get
            {
                object obj = ResourceManager.GetObject("chevron_small_collapse", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage clipboard_paste
        {
            get
            {
                object obj = ResourceManager.GetObject("clipboard_paste", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control
        {
            get
            {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_double
        {
            get
            {
                object obj = ResourceManager.GetObject("control_double", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_double_180
        {
            get
            {
                object obj = ResourceManager.GetObject("control_double_180", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_pause
        {
            get
            {
                object obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_skip
        {
            get
            {
                object obj = ResourceManager.GetObject("control_skip", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_stop
        {
            get
            {
                object obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage control_stop_180
        {
            get
            {
                object obj = ResourceManager.GetObject("control_stop_180", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cresc1
        {
            get
            {
                object obj = ResourceManager.GetObject("cresc1", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cresc2
        {
            get
            {
                object obj = ResourceManager.GetObject("cresc2", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cresc3
        {
            get
            {
                object obj = ResourceManager.GetObject("cresc3", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cresc4
        {
            get
            {
                object obj = ResourceManager.GetObject("cresc4", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cresc5
        {
            get
            {
                object obj = ResourceManager.GetObject("cresc5", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage cross_small
        {
            get
            {
                object obj = ResourceManager.GetObject("cross_small", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage dim1
        {
            get
            {
                object obj = ResourceManager.GetObject("dim1", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage dim2
        {
            get
            {
                object obj = ResourceManager.GetObject("dim2", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage dim3
        {
            get
            {
                object obj = ResourceManager.GetObject("dim3", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage dim4
        {
            get
            {
                object obj = ResourceManager.GetObject("dim4", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage dim5
        {
            get
            {
                object obj = ResourceManager.GetObject("dim5", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage disk
        {
            get
            {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage disk__plus
        {
            get
            {
                object obj = ResourceManager.GetObject("disk__plus", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage documents
        {
            get
            {
                object obj = ResourceManager.GetObject("documents", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage drive
        {
            get
            {
                object obj = ResourceManager.GetObject("drive", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage edit_list_order
        {
            get
            {
                object obj = ResourceManager.GetObject("edit_list_order", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage end_marker
        {
            get
            {
                object obj = ResourceManager.GetObject("end_marker", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage eraser
        {
            get
            {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage folder
        {
            get
            {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage folder__plus
        {
            get
            {
                object obj = ResourceManager.GetObject("folder__plus", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage folder_horizontal_open
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_horizontal_open", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   (アイコン) に類似した型 Xwt.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
		internal static Xwt.Drawing.BitmapImage Icon1
        {
            get
            {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
				return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage layer_shape_curve
        {
            get
            {
                object obj = ResourceManager.GetObject("layer_shape_curve", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage layer_shape_line
        {
            get
            {
                object obj = ResourceManager.GetObject("layer_shape_line", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage minus8x8
        {
            get
            {
                object obj = ResourceManager.GetObject("minus8x8", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note001
        {
            get
            {
                object obj = ResourceManager.GetObject("note001", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note002
        {
            get
            {
                object obj = ResourceManager.GetObject("note002", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note004
        {
            get
            {
                object obj = ResourceManager.GetObject("note004", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note008
        {
            get
            {
                object obj = ResourceManager.GetObject("note008", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note016
        {
            get
            {
                object obj = ResourceManager.GetObject("note016", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note032
        {
            get
            {
                object obj = ResourceManager.GetObject("note032", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note064
        {
            get
            {
                object obj = ResourceManager.GetObject("note064", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage note128
        {
            get
            {
                object obj = ResourceManager.GetObject("note128", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage notenull
        {
            get
            {
                object obj = ResourceManager.GetObject("notenull", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage pencil
        {
            get
            {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage piano
        {
            get
            {
                object obj = ResourceManager.GetObject("piano", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage pin__arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("pin__arrow", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage pin__arrow_inv
        {
            get
            {
                object obj = ResourceManager.GetObject("pin__arrow_inv", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage plus8x8
        {
            get
            {
                object obj = ResourceManager.GetObject("plus8x8", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage ruler_crop
        {
            get
            {
                object obj = ResourceManager.GetObject("ruler_crop", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage scissors
        {
            get
            {
                object obj = ResourceManager.GetObject("scissors", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage slash
        {
            get
            {
                object obj = ResourceManager.GetObject("slash", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage splash
        {
            get
            {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage start_marker
        {
            get
            {
                object obj = ResourceManager.GetObject("start_marker", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage target__pencil
        {
            get
            {
                object obj = ResourceManager.GetObject("target__pencil", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }

        /// <summary>
        ///   型 Xwt.Drawing.BitmapImage のローカライズされたリソースを検索します。
        /// </summary>
        internal static Xwt.Drawing.BitmapImage VSTonWht
        {
            get
            {
                object obj = ResourceManager.GetObject("VSTonWht", resourceCulture);
                return ((Xwt.Drawing.BitmapImage)(obj));
            }
        }
    }
}
